### ISSUE TITLE
TypeError: u.avatar_urls is undefined

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wporg-internal-notes#5]
Getting this error when attempting to add a new note on a pattern post in the Pattern Directory.

**Comment by ryelle** [comment]
The issue here was that the `author` does not exist on the patterns site, so the value for `author` was actually an error:

```
{
	...
	"_embedded": {
		"author": [
			{
				"code": "rest_user_invalid_id",
				"message": "Invalid user ID.",
				"data": {
					"status": 404
				}
			}
		]
	}
}
```

A check for `avatar_urls` or whether `author` is an error around here should fix the issue.

https://github.com/WordPress/wporg-internal-notes/blob/4e2c08d2fee2eab068b1b282c6c044a0a77f1331/source/wp-content/plugins/wporg-internal-notes/src/notes-list/notes-list-item.js#L98
